[build]
  command = "npm run generate"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "16"

[forms]
  # Specify the forms to be detected by Netlify
  [forms.uwm-partner-contact]
    # This ensures the form is explicitly detected

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 